import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { DrawingProvider } from "@/context/DrawingContext";
import Navbar from "@/components/Navbar"; // Fixed case issue
import ZoomSelection from "@/components/ZoomSelection";
import SelectionWindow from "@/components/SelectionWindow";
import UndoRedo from "@/components/UndoRedo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
        <DrawingProvider>
          <Navbar />
          <SelectionWindow />
          {children}
          <div className="fixed bottom-4 left-10 flex gap-4">
            <div className="backdrop-blur-md bg-violet-100 shadow-lg rounded-lg px-4 py-2 z-50">
              <ZoomSelection />
            </div>
            <div className="backdrop-blur-md bg-violet-100 shadow-lg rounded-lg px-4 py-2 z-50">
              <UndoRedo />
            </div>
          </div>
        </DrawingProvider>
      </body>
    </html>
  );
}
